version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: "npm run dev"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/portfolio
      - ENV=dev

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: