import type { Metadata } from "next";
import "./globals.css";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Schibsted_Grotesk, Space_Grotesk, Bricolage_Grotesque} from "next/font/google";
// import { Inter, Inter_Tight, Roboto} from "next/font/google";
import {
  Bebas_Neue,
  Space_Grotesk,
  Schibsted_Grotesk,
  Inter,
  Inter_Tight,
  // Roboto,
} from "next/font/google";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
  subsets: ["latin"],
});
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  weight: ["500", "600"],
  subsets: ["latin"],
});
const schiGrotesk = Schibsted_Grotesk({
  variable: "--font-schi-grotesk",
  weight: ["700", "600"],
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  weight: ["700", "600"],
  subsets: ["latin"],
});
const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  weight: ["700", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${spaceGrotesk.variable} ${schiGrotesk.variable} ${inter.variable} ${interTight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
